"""
配置包初始化文件
"""

from .prompts import (
    AGENT_CORE_SYSTEM_PROMPT,
    MULTIMODAL_IMAGE_PROMPT,
    MULTIMODAL_VIDEO_PROMPT,
    VOICE_INTERACTION_PROMPT,
    REQUIREMENT_COMPLETION_PROMPT,
    ITINERARY_GENERATION_PROMPT,
    ITINERARY_ADJUSTMENT_PROMPT,
    EMERGENCY_SOLUTION_PROMPT,
    SCENARIO_PROMPTS,
    get_combined_prompt
)

__all__ = [
    'AGENT_CORE_SYSTEM_PROMPT',
    'MULTIMODAL_IMAGE_PROMPT',
    'MULTIMODAL_VIDEO_PROMPT',
    'VOICE_INTERACTION_PROMPT',
    'REQUIREMENT_COMPLETION_PROMPT',
    'ITINERARY_GENERATION_PROMPT',
    'ITINERARY_ADJUSTMENT_PROMPT',
    'EMERGENCY_SOLUTION_PROMPT',
    'SCENARIO_PROMPTS',
    'get_combined_prompt'
]
